### ISSUE TITLE
Just beds

### ISSUE THREAD

**Issue by DerShendi** [eleksploded/BetterBedsMod#2]
Do i need to say more just look at the post
 https://www.reddit.com/r/softwaregore/comments/c6jmbk/bed_i_just_added_a_bunch_of_mods_in_mc_1142_dunno/
once i removed the mod everything worked fine 
i just saw the description of the mod xD
Sorry i thought it fixed some bed issues MC has

**Comment by eleksploded** [comment]
Yeah... I get that a lot. No one reads what it does before downloading it. IMO, I think its kinda funny.
